# base configurations
dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

git:
  submodules: false

env:
  - PIPENV_SKIP_LOCK=1

# command to install dependencies
install:
  - pip install pipenv
  - pipenv install --dev

# command to run tests
script:
  - cd test && coverage run test_extractor.py

# coverage
after_success:
  - codecov
#  - pylint --load-plugins=pylint.extensions.check_elif,pylint.extensions.docstyle,pylint.extensions.emptystring,pylint.extensions.overlapping_exceptions --disable=all --enable=F,E,W,R,basic,classes,format,imports,refactoring,else_if_used,docstyle,compare-to-empty-string,overlapping-except --disable=blacklisted-name,invalid-name,missing-class-docstring,missing-function-docstring,missing-module-docstring,design,too-many-lines,eq-without-hash,old-division,no-absolute-import,input-builtin,too-many-nested-blocks,broad-except,singleton-comparison --max-line-length=120 --init-import=yes --msg-template='{line},{column},{category},{symbol}:{msg}' --reports=n --output-format=text pcapkit
#  - bandit -f custom --msg-template {line},0,{severity},{test_id}:{msg} -n -1 -r pcapkit
#  - mypy --ignore-missing-imports --follow-imports=silent --show-column-numbers pcapkit
