{% set name = "pypcapkit" %}
#{% set version = "1.0.0b9" %}

package:
  name: {{ name }}
  version: "{{ environ['PCAPKIT_VERSION'] }}"

#source:
#  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
#  sha256: 6789d9aa44564091a4fdeaf65c694303c1b5a16474568842aa9ca9d931aac448

source:
  git_url: https://github.com/JarryShaw/PyPCAPKit.git
  git_rev: "v{{ environ['PCAPKIT_VERSION'] }}"
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: 1
  entry_points:
    - pcapkit-cli = pcapkit.__main__:main
    - pcapkit-vendor = pcapkit.vendor.__main__:main
  script: "{{ PYTHON }} -m pip install .[all] -vv"

requirements:
  build:
    - git
  host:
    - pip
    - python
  run:
    - python

#test:
#  imports:
#    - pcapkit

about:
  home: https://jarryshaw.github.io/PyPCAPKit
  license: BSD 3-Clause License
  license_family: BSD
  license_file:
    - LICENSE
  summary: "PyPCAPKit: comprehensive network packet analysis library"
  doc_url: https://jarryshaw.github.io/PyPCAPKit
  dev_url: https://github.com/jarryshaw/pypcapkit

extra:
  recipe-maintainers:
    - jarryshaw
