channels:    # write here the list of channels to look for your library dependencies
  - uibcdf
  - conda-forge
  - defaults

dependencies:   # Keep this block with only the conda build tools
  - conda-build
