# -*- coding: utf-8 -*-
"""``from_dict(to_dict())`` rebuilds nested values, and ``len`` matches iteration.

GitHub issue #1290: :meth:`Schema.to_dict
<pcapkit.protocols.schema.schema.Schema.to_dict>` flattens a nested schema
into a :obj:`dict`, and :meth:`SchemaField.pack
<pcapkit.corekit.fields.misc.SchemaField.pack>` then called ``.pack`` on that
dict. :meth:`Info.from_dict <pcapkit.corekit.infoclass.Info.from_dict>` kept
the flattened dict too, so ``info.inner.x`` raised.

GitHub issue #1296: :meth:`Info.__len__
<pcapkit.corekit.infoclass.Info.__len__>` counted the ``__excluded__``
bookkeeping keys that iteration skips.

The PCAP-NG cases build their blocks as octets in memory rather than reading a
capture: :file:`examples/captures/` is generated by
:file:`examples/generators/make_samples.py` and is not tracked, so the unit
tier has no captures to read.

Every class is declared inside its test, after
:func:`~tests._support.reimport_once_per_class`, so it binds the live
:mod:`pcapkit` import rather than one an earlier module has purged.

"""

import gc
import unittest

from tests._support import reimport_once_per_class

#: PCAP-NG blocks, little-endian, one per block schema that claims a type code.
#: Each nests its body in :attr:`PCAPNG.block
#: <pcapkit.protocols.schema.misc.pcapng.PCAPNG.block>`, which is the
#: :class:`~pcapkit.corekit.fields.misc.SchemaField` issue #1290 is about.
PCAPNG_BLOCKS = {
    'shb': '0a0d0d0a' '1c000000' '4d3c2b1a' '0100' '0000' 'ffffffffffffffff' '1c000000',
    'shb-options': ('0a0d0d0a' '28000000' '4d3c2b1a' '0100' '0000' 'ffffffffffffffff'
                    '0100' '0400' '61626364' '0000' '0000' '28000000'),
    'idb': '01000000' '14000000' '0100' '0000' '00000400' '14000000',
    'idb-options': ('01000000' '20000000' '0100' '0000' '00000400'
                    '0900' '0100' '06000000' '0000' '0000' '20000000'),
    'epb': ('06000000' '24000000' '00000000' '00000000' '0a000000'
            '04000000' '04000000' '61626364' '24000000'),
    'spb': '03000000' '14000000' '04000000' '61626364' '14000000',
    'nrb': '04000000' '10000000' '0000' '0000' '10000000',
    'isb': '05000000' '18000000' '00000000' '00000000' '0a000000' '18000000',
    'dsb': '0a000000' '18000000' '544c534b' '04000000' '61626364' '18000000',
    'cb': 'ad0b0000' '14000000' 'ad0b0000' '61626364' '14000000',
    'sjeb': '09000000' '10000000' '61626364' '10000000',
    'unknown-type': 'ff7f0000' '10000000' '61626364' '10000000',
}


class TestSchemaFromDictRoundTrip(unittest.TestCase):
    """GitHub issue #1290, the :class:`Schema` half."""

    def setUp(self) -> None:
        reimport_once_per_class(self)

    def _schemas(self):  # type: ignore[no-untyped-def]
        from pcapkit.corekit.fields.misc import SchemaField
        from pcapkit.corekit.fields.numbers import UInt8Field
        from pcapkit.protocols.schema.schema import Schema, schema_final

        @schema_final
        class In(Schema):
            x: int = UInt8Field()

        @schema_final
        class Out(Schema):
            inner: In = SchemaField(length=1, schema=In)
            tail: int = UInt8Field()

        return In, Out

    def test_from_dict_of_to_dict_packs_nested_schema(self) -> None:
        _, Out = self._schemas()
        raw = b'\x07\x09'
        parsed = Out.unpack(raw, len(raw), None)
        self.assertEqual(Out.from_dict(parsed.to_dict()).pack(), raw)

    def test_schema_value_still_packs_as_is(self) -> None:
        In, Out = self._schemas()
        self.assertEqual(Out.from_dict(inner=In(x=3), tail=4).pack(), b'\x03\x04')

    def test_pcapng_block_schemas_round_trip(self) -> None:
        from pcapkit.protocols.schema.misc.pcapng import PCAPNG

        for name, hexed in PCAPNG_BLOCKS.items():
            raw = bytes.fromhex(hexed)
            with self.subTest(block=name):
                schema = PCAPNG.unpack(raw, len(raw), None)
                self.assertEqual(schema.pack(), raw)
                self.assertEqual(type(schema).from_dict(schema.to_dict()).pack(), raw)


class TestInfoFromDictRoundTrip(unittest.TestCase):
    """GitHub issue #1290, the :class:`Info` half."""

    def setUp(self) -> None:
        reimport_once_per_class(self)

    def test_annotated_nested_info_is_rebuilt(self) -> None:
        from typing import Optional

        from pcapkit.corekit.infoclass import Info, info_final

        @info_final
        class In(Info):
            x: int

        @info_final
        class Out(Info):
            inner: In
            maybe: Optional[In]
            y: int

        info = Out(inner=In(x=1), maybe=In(x=2), y=3)
        rebuilt = Out.from_dict(info.to_dict())
        self.assertIsInstance(rebuilt.inner, In)
        self.assertIsInstance(rebuilt.maybe, In)
        self.assertEqual((rebuilt.inner.x, rebuilt.maybe.x, rebuilt.y), (1, 2, 3))
        # NOTE: the pairs rather than the two exports: an OrderedMultiDict compares
        # its values with ``!=``, which for a nested one compares its buckets.
        self.assertEqual(list(rebuilt.to_dict().items(multi=True)), list(info.to_dict().items(multi=True)))

    def test_string_annotation_in_a_data_module_is_resolved(self) -> None:
        from pcapkit.protocols.data.application.httpv2 import DataFrame, DataFrameFlags

        frame = DataFrame.from_dict({'flags': {'END_STREAM': True, 'PADDED': False}})
        self.assertIsInstance(frame.flags, DataFrameFlags)
        self.assertTrue(frame.flags.END_STREAM)

    def test_unannotated_or_unresolvable_key_stays_a_dict(self) -> None:
        from pcapkit.corekit.infoclass import Info, info_final

        @info_final
        class Out(Info):
            inner: 'NoSuchType'  # type: ignore[name-defined] # noqa: F821

        info = Out.from_dict({'inner': {'x': 1}, 'extra': {'z': 2}})
        self.assertEqual(info.inner, {'x': 1})
        self.assertEqual(info.extra, {'z': 2})

    def test_container_annotation_does_not_raise(self) -> None:
        """A ``list[Info]`` annotation is skipped, not fed to :func:`issubclass`.

        Below Python 3.11 such an annotation satisfies ``isinstance(hint,
        type)``, so an unguarded :func:`issubclass` raised :exc:`TypeError` out
        of :meth:`~pcapkit.corekit.infoclass.Info.from_dict` -- measured on
        3.10 for 26 of 487 :class:`~pcapkit.corekit.infoclass.Info` classes,
        including :class:`~pcapkit.foundation.reassembly.data.ip.Packet`.

        """
        from typing import Dict, List

        from pcapkit.corekit.infoclass import Info, info_final

        @info_final
        class In(Info):
            x: int

        @info_final
        class Out(Info):
            entries: List[In]
            mapped: Dict[str, In]
            builtin: 'list[In]'

        info = Out.from_dict({'entries': [{'x': 1}], 'mapped': {'a': {'x': 2}},
                              'builtin': [In(x=3)]})
        self.assertEqual(info.entries, [{'x': 1}])
        self.assertEqual(info.mapped, {'a': {'x': 2}})
        self.assertIsInstance(info.builtin[0], In)

    def test_reassembly_packet_from_dict_still_works(self) -> None:
        from pcapkit.foundation.reassembly.data.ip import Packet

        self.assertEqual(Packet.from_dict({'bufid': 1}).bufid, 1)


class NestedTypeResolverTests(unittest.TestCase):
    """The annotation resolver behind :meth:`Info.from_dict`."""

    def setUp(self) -> None:
        reimport_once_per_class(self)

    def test_a_generic_alias_shape_is_skipped_rather_than_raising(self) -> None:
        """Pin the Python 3.9/3.10 :class:`types.GenericAlias` shape.

        There, ``isinstance(list[In], type)`` is :data:`True` while
        :func:`issubclass` refuses the same object with :exc:`TypeError`. From
        3.11 on the ``isinstance`` is already :data:`False`, so the object below
        mimics the older shape -- its ``__class__`` reports :class:`type`, which
        is what makes :func:`isinstance` agree and :func:`issubclass` object.

        """
        from pcapkit.corekit.infoclass import _as_info_type

        class FakeGenericAlias:
            """An object :func:`isinstance` reads as a class and :func:`issubclass` does not."""

            @property
            def __class__(self):  # type: ignore[override]
                return type

        alias = FakeGenericAlias()
        self.assertIsInstance(alias, type)
        with self.assertRaises(TypeError):
            issubclass(alias, int)  # type: ignore[arg-type]
        self.assertIsNone(_as_info_type(alias))

    def test_resolver_answers(self) -> None:
        from typing import List, Optional, Union

        from pcapkit.corekit.infoclass import Info, _as_info_type, info_final

        @info_final
        class In(Info):
            x: int

        self.assertIs(_as_info_type(In), In)
        self.assertIs(_as_info_type(Optional[In]), In)
        for hint in (int, None, 'In', List[In], Union[In, int]):
            with self.subTest(hint=hint):
                self.assertIsNone(_as_info_type(hint))

    def test_cache_is_per_class_and_collectable(self) -> None:
        """A self-referential class is still collected.

        The map is cached on the class, not in a module-level
        :class:`weakref.WeakKeyDictionary`: there the cached value strongly
        references the class the weak key points at, so a class annotated with
        itself could never be collected.

        """
        import weakref

        from pcapkit.corekit.infoclass import Info, _nested_info_types, info_final

        @info_final
        class Node(Info):
            nxt: int

        # NOTE: the annotation is rebound to the class object itself, because a
        # locally declared class is not resolvable by name from its module's
        # globals, and ``Optional[Node]`` would be pinned by :mod:`typing`'s own
        # argument cache and so never collected whatever this code does.
        Node.__annotations__['nxt'] = Node

        self.assertIn('nxt', _nested_info_types(Node))
        self.assertIn('__nested_info_types__', Node.__dict__)

        ref = weakref.ref(Node)
        del Node
        gc.collect()
        self.assertIsNone(ref())

    def test_a_subclass_does_not_inherit_its_parents_map(self) -> None:
        from pcapkit.corekit.infoclass import Info, _nested_info_types, info_final

        @info_final
        class In(Info):
            x: int

        class Base(Info):
            inner: In

        @info_final
        class Derived(Base):
            other: int

        self.assertEqual(_nested_info_types(Base), {'inner': In})
        self.assertEqual(_nested_info_types(Derived), {'inner': In})
        self.assertNotIn('__nested_info_types__', Base.__dict__.get('__annotations__', {}))


class TestInfoLen(unittest.TestCase):
    """GitHub issue #1296."""

    def setUp(self) -> None:
        reimport_once_per_class(self)

    def test_len_matches_iteration(self) -> None:
        from pcapkit.corekit.infoclass import Info, info_final

        @info_final
        class I(Info):
            a: int

        info = I(a=1)
        self.assertEqual(list(info), ['a'])
        self.assertEqual(len(info), 1)
        self.assertEqual(len(Info()), 0)

    def test_len_counts_renamed_builtin_keys(self) -> None:
        from pcapkit.corekit.infoclass import Info

        info = Info.from_dict({'keys': 1, 'b': 2})
        self.assertEqual(len(info), len(list(info)))
        self.assertEqual(len(info), 2)


if __name__ == '__main__':
    unittest.main()
