{% set name = "pypcapkit" %}
{% set version = environ['PCAPKIT_VERSION'] %}
{% set build_number = environ['PCAPKIT_BUILD'] %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  path: ../..
  #git_url: https://github.com/JarryShaw/PyPCAPKit.git
  #git_rev: "conda-{{ version }}+{{ build_number }}"
  #git_depth: 1 # (Defaults to -1/not shallow)

build:
  number: {{ build_number }}
  entry_points:
    - pcapkit-cli = pcapkit.__main__:main
    - pcapkit-vendor = pcapkit.vendor.__main__:main
  #script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - git
    - python
    - pip
    - setuptools>=61.0.0

    # # version compatibility
    # - bpc-f2format
    # - bpc-poseur
    # - bpc-walrus

    # - dictdumper~=0.8.0  # for formatted output
    # - chardet            # for bytes decode
    # - aenum              # for const types
    # - tbtrim>=0.2.1      # for refined exceptions

    # # version compatibility
    # - pathlib2>=2.3.2
    # - typing-extensions

    # - emoji
    # - dpkt
    # - scapy
    # - pyshark
    # - requests[socks]
    # - beautifulsoup4[html5lib]
  host:
    - python
    - pip
    - setuptools>=61.0.0

    # # version compatibility
    # - bpc-f2format
    # - bpc-poseur
    # - bpc-walrus

    # - dictdumper~=0.8.0  # for formatted output
    # - chardet            # for bytes decode
    # - aenum              # for const types
    # - tbtrim>=0.2.1      # for refined exceptions

    # # version compatibility
    # - pathlib2>=2.3.2
    # - typing-extensions

    # - emoji
    # - dpkt
    # - scapy
    # - pyshark
    # - requests[socks]
    # - beautifulsoup4[html5lib]
  run:
    - python

    # - dictdumper~=0.8.0  # for formatted output
    # - chardet            # for bytes decode
    # - aenum              # for const types
    # - tbtrim>=0.2.1      # for refined exceptions

    # # version compatibility
    # - pathlib2>=2.3.2
    # - typing-extensions

    # - emoji
    # - dpkt
    # - scapy
    # - pyshark
    # - requests[socks]
    # - beautifulsoup4[html5lib]

test:
 imports:
   - pcapkit

about:
  home: https://jarryshaw.github.io/PyPCAPKit
  license: BSD 3-Clause License
  license_family: BSD
  license_file:
    - LICENSE
  summary: "PyPCAPKit: comprehensive network packet analysis library"
  doc_url: https://jarryshaw.github.io/PyPCAPKit
  dev_url: https://github.com/jarryshaw/pypcapkit

extra:
  recipe-maintainers:
    - jarryshaw
