on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_run:
    workflows: [ "Vendor Update" ]
    types:
      - completed

name: Create Release

jobs:
  release:
    name: GitHub Release
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and Build
        run: |
          set -x

          brew install python@3.11 || true
          brew unlink python@3.11 || true
          brew link --force --overwrite python@3.11

          python3 -m pip install -U pip setuptools wheel
          python3 -m pip install -U build twine

          # PyPI distro
          python3 -m build

          # TODO: Anaconda distro

          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Create Release
        id: create_release
        uses: marvinpinto/action-automatic-releases@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.ref }}
          title: PyPCAPKit ${{ github.ref }}
          prerelease: ${{ contains(github.ref, 'pre') || contains(github.ref, 'a') || contains(github.ref, 'b') || contains(github.ref, 'rc') }}
          files: |
            dist/*
